### ISSUE TITLE
Draw on background?

### ISSUE THREAD

**Issue by Orionox** [ClipplerBlood/sketch-tiles#2]
It would be phenomenal if we could draw on a background image.

**Comment by ClipplerBlood** [comment]
You actually can!
You have to set the "Import SVG" option to an SVG image
If you also set it as default, it will always be imported when starting a new sketch.

Only caveat is that it *must* be an SVG due to how Foundry renders SVG in the canvas. I've already tried to add the option to import raster images (PNG, JPG, etc) which works fine when creating the sketch SVG, but once a tile is created in the scene the background disappears.

Example:
![adding-bg](https://user-images.githubusercontent.com/82539651/197202019-fa4fdea7-21d0-43ef-96c8-c5453302b528.gif)
